language: node_js
node_js: '8'
cache: yarn
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --ignore-scripts
script:
  - yarn build
